name: Deploy to S3

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install # Adjust this command as needed

      - name: Build frontend
        run: npm run build # Adjust this command as needed

      - name: Configure AWS credentials
        run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ap-southeast-1 # Adjust the region as needed

      - name: Upload to S3
        run: aws s3 cp build/ s3://clothes.io-frontend/ --recursive # Replace 'your-s3-bucket' with your actual S3 bucket name and adjust the source directory if needed

